apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-production
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ms-production
  template:
    metadata:
      labels:
        app: ms-production
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: lealfelipealves/fiap-soat-ms-production:latest
          ports:
            - containerPort: 3333
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ms-production-config
            - secretRef:
                name: ms-production-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
