apiVersion: v1
data:
  APP_PORT: MzMzNA==
  DB_PORT: MzMwNg==
  DB_ROOT_PASSWORD: MTIzUGEkJDJxRmlUZ1NJRTFEdUxlOU1jZA==
  DB_DATABASE: ZmlhcC1zb2F0LW1zLXByb2R1Y3Rpb24=
  DB_URL: bXlzcWw6Ly9maWFwc29hdHVzZXI6MTIzUGEkJDJxRmlUZ1NJRTFEdUxlOU1jZEBsb2NhbGhvc3Q6MzMwNi9maWFwLXNvYXQtbXMtcHJvZHVjdGlvbg==
kind: Secret
metadata:
  name: backend-secret
  namespace: fiap